#!/bin/sh
# Send FIO statistics to perf server
pgm="${0##*/}"		# Program basename
progdir="${0%/*}"	# Program directory

set -e
. ${progdir}/config
. ${progdir}/subr/system.subr
. ${progdir}/subr/network.subr
set +e

#
#data="/tmp/x5.tgz"
#curl -sS -X POST -H "Content-Type: application/gzip" --data-binary "@$data" ${checkin_server}/scripts/report_system.php?token=ssssssssssssssssss

## MAIN: processing begins here
##
# network setup
setup_proxies

echo "Checkin server: ${checkin_server}"
url="${checkin_server}"

_ret=0
test_connection

log "INIT" "Connected to ${checkin_server_description}"

# prepare
get_id_token
_ret=$?

# begin
enable_token
report_system
disable_token

exit ${_ret}
